name: Deploy

on:
  push:
    branches:
      - 'master'
jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
    - run: yarn install
    - run: yarn build
    - run: echo 'geekinstructables.com' > docs/.vuepress/dist/CNAME
    - name: Deploy
      env:
          DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
          GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
      run: |
        git config --global user.email "$GIT_EMAIL"
        git config --global user.name "GitHub CI runner"
        cd docs/.vuepress/dist
        git init
        git add -A
        git commit -m "New deployment"
        git push -f "https://$DEPLOY_TOKEN@github.com/jesusgn90/geek-instructables.git" master:gh-pages
