name: Pull request CI

on:
  push:
    branches:
      - '!master'
      - '!gh-pages'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
    - run: yarn install
    - run: yarn build
